### ISSUE TITLE
Add a Logger class

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#136]
# Requirements:
- Can print ~~timestamp~~, line number and filename. [LOG_LEVEL][TIMESTAMP](filename : line number): LOG MESSAGE
- ~~At least two levels of logging (info and error)~~
- The enable/disable logs from a specific

# Specs:
- The logging maco looks like `LOG(condition, msg)`
- Logging message looks like `[filename:line_number]msg`
  - `__FILE__` ,` __LINE__` are built-in macros you can use
- Can be just a header `log.h` where macros are defined
- The macro wraps `Serial.print` function call
# Nice to have
- It would be nice if we do not have to type `condition` in every function call and maintain the same functionality.

**Comment by RyanL17** [comment]
https://www.drdobbs.com/cpp/logging-in-c/201804215

https://cppcodetips.wordpress.com/2014/01/02/a-simple-logger-class-in-c/

**Comment by RyanL17** [comment]
https://github.com/amrayn/easyloggingpp

**Comment by tarek20501** [comment]
Add log when logger initialized and fix esp32 logs

**Comment by tarek20501** [comment]
- [ ] fix missing new lines in logged file
