### ISSUE TITLE
Unix timestamp is incomplete

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#137]
timestamp on particle is incomplete. It is missing few digits from the left.
```
15.10,16.10,17.10,18.10,19.10,944006931
```

**Comment by jack5661** [comment]
@tarek20501 I can't reproduce this issue?
![image](https://user-images.githubusercontent.com/34701860/124364598-6aca9b00-dbf7-11eb-9562-41af2e730ebc.png)

**Comment by tarek20501** [comment]
@ShreyansK2000 I saw this again today on my electron but @jack5661 does not see it on boron.
Could you check on your electron?

**Comment by tarek20501** [comment]
When gsm is turned off the rtc does not work
