### ISSUE TITLE
Explore Ditching RTC Module

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#57]
Given a Unix timestamp (example 1604168465) , can we keep track of time for at least 24 hours after ESP32 have received the Unix timestamp from Particle.

- Figure out if hardware support exist
- If it does find relevant Arduino API calls
- Experiment with it 

Resources:
https://github.com/espressif/arduino-esp32
https://www.espressif.com/sites/default/files/documentation/esp32-wrover-e_esp32-wrover-ie_datasheet_en.pdf
https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf

**Comment by jack5661** [comment]
Potentially Useful Sites:

* https://arduino.stackexchange.com/questions/72010/set-the-wall-clock-time-or-change-gmt-offset-without-ntp-server
* https://github.com/espressif/esp-idf/blob/master/components/newlib/time.c
* https://github.com/espressif/esp-idf/blob/98e5c475b31ce704e08bd1a48f5d2de3f0b216b0/components/newlib/include/sys/time.h
* https://github.com/espressif/arduino-esp32/issues/120
* https://github.com/espressif/esp-idf/blob/98e5c475b31ce704e08bd1a48f5d2de3f0b216b0/components/newlib/include/sys/time.h
* https://www.reddit.com/r/esp32/comments/87tgsh/how_to_configure_time_without_using_ntp_server/
