### ISSUE TITLE
Make Releases on GitHub

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#60]
- We want our customer to be able to conveniently download our flashable firmware binaries for all boards
- figure out how to flash without setting up the dev environment

**Comment by jack5661** [comment]
![image](https://user-images.githubusercontent.com/34701860/113491458-d3359f00-9485-11eb-87ea-4420c198a321.png)

[Flash Tool Guide](https://docs.espressif.com/projects/esp-at/en/latest/Get_Started/Downloading_guide.html)
[Flash Tool Download](https://www.espressif.com/en/support/download/other-toolsl)

Run this command to see where the binaries get downloaded to what address: *pio run -v -t upload*
