### ISSUE TITLE
Voltage sensor schematics

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#69]

**Comment by tarek20501** [comment]
![voltage_divider_symbol](https://user-images.githubusercontent.com/39224871/97786485-1e5f2500-1b69-11eb-9376-566a1bbcf238.PNG)

**Comment by RyanL17** [comment]
Farm Prototype Voltage Sensor Resistor Values: 

- RH: 1M

- RL: 25K
