### ISSUE TITLE
Revise LED Pattern

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#74]
Review pin assignments

We need to  determine a pattern for the LED on Particle and ESP32 to let the user know that the system is initialized and operating nominally
Neither Particle  nor ESP32 has a built in LED.

Deadline: End of 2020W2

**Comment by jack5661** [comment]
**LED Patterns:**

**Initializing** - Quickly blinking LED
**Initialized** - Let LED stay solid for 1 minute to signify everything is okay then turn off to save power
**Initializing Failed** - Turn LED off for 10 seconds then blink LED every 5 seconds 
**Low Battery/File Space** - Blink LED every 10 seconds

**Comment by jack5661** [comment]
Need infrastructure or way to tell if setup has failed.

**Comment by RyanL17** [comment]
New LED Pattern:

LED OFF: Initialization Complete
Flashing While Initializing: On when entering initialization function, Off when back to main
LED ON: Initialization Failed
