### ISSUE TITLE
Investigate the scope of changes for Boron

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#80]
Particle is discontinuing Electron 😢. We have decided to use Boron. We need to investigate what we need to change to swap the Electron
Deadline: Before Particle Boron is ordered

**Comment by lcfyi** [comment]
This is actually something I came across as an issue in another project, so I figured I'd chime in here. Fwiw, Particle still supports the Electron, but supply might dwindle.

The main difference between the two is IO. The Electron is also 5V-tolerant for most of their pins, but the Boron maxes out at 3.3. As for the exact IO differences, I've copied the table below. The difference in UART IO was a huge problem for me, but it might not be in your case? 


# IO

## Electron

Peripheral Type | Qty | Input(I) / Output(O) | FT[1] / 3V3[2]
-- | -- | -- | --
Digital | 30 | I/O | FT/3V3
Analog (ADC) | 12 | I | 3V3
Analog (DAC) | 2 | O | 3V3
UART | 3 | I/O | 3V3
SPI | 2 | I/O | 3V3
I2S | 1 | I/O | 3V3
I2C | 1 | I/O | FT
CAN | 2 | I/O | 3V3[4]
USB | 1 | I/O | 3V3
PWM | 133 | O | 3V3


## Boron

Peripheral Type | Qty | Input(I) / Output(O)
-- | -- | --
Digital | 20 | I/O
Analog (ADC) | 6 | I
UART | 1 | I/O
SPI | 1 | I/O
I2C | 2 | I/O
USB | 1 | I/O
PWM | 8 | O
