### ISSUE TITLE
Add current sensor (HSTS016L) support

### ISSUE THREAD

**Issue by tarek20501** [Sustaingineering/Pump-Firmware#83]
Add initial support for new current sensor

Deadline: Feb 13th meeting

**Comment by tarek20501** [comment]
@forbes-choy 
Please comment the new equation that converts the analog output to current in Amps

**Comment by tarek20501** [comment]
https://cdn.shopifycdn.net/s/files/1/2723/6858/files/HSTS016L_a7e0ee3a-45cc-4504-95cc-f8ae5a5ae776.pdf?v=1614127414
![image](https://user-images.githubusercontent.com/39224871/126911148-0f6bdbd7-eaf0-41c2-8283-1ddfe975eaa5.png)

`V = 2.5 + (I/I_PN) * 0.625` where `I_PN` is rated input
`I = (V - 2.5) * (I_PN/0.625)`

**Comment by tarek20501** [comment]
@forbes-choy Let me know if I got this correctly...

```
#define I_PN 10 // can be 10,  20, 30, 50, 100, 150, or 200
float Current::readRaw()
{
    int analogData = analogRead(m_pin); // Take reading
    // Convert to decimal
    float hallVoltage = analogData * (m_maximumVoltage / analogDigitalConversionResolution);
    // Compute the current from the voltage reading equation
    float hallAmps = (hallVoltage - 2.5) * (I_PN / 0.625);
    return hallAmps;
}
```

**Comment by forbes-choy** [comment]
@tarek20501 your Current::readRaw() function looks good to me. We will test the hardware ASAP
